### ISSUE TITLE
Singularity 3.0.0 (moving to Go)

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/singularity-feedstock#11]
As of Singularity 3.0.0, we will need to switch the build to use Go as it has been totally rewritten in Go. Leaving this here as a note so that we remember to do this. Also may be good to try building the alpha just to see what issues come up.

**Comment by bgruening** [comment]
@jakirkham Go is compiling static binaries. So we might just fetch the upstream once?

**Comment by jakirkham** [comment]
Generally we try to build from source. I don't expect this to be too bad as we have a Go compiler and already some best practices are forming around Go. Though we likely will need input from @sodre on how best to proceed here.

**Comment by jakirkham** [comment]
The bot missed the update because they renamed the GitHub org. Have updated the URL in the recipe. We should see an update PR soon.

**Comment by sodre** [comment]
nice!

**Comment by sodre** [comment]
wow.. their new make system is <strike>horrible</strike> very difficult to work with...

**Comment by jakirkham** [comment]
Hmm...yeah this looks interesting. Guess they have a shell script that creates the `Makefile`? Their old build system used `autoconf` and `automake` with distributions having already run this, which worked reasonably well. Wonder what motivated the switch. 😕

**Comment by sodre** [comment]
I am not sure either.... the good news is that I have a semi-working (it compiles) version on my linux build servers.

I'll open a PR soon...

**Comment by jakirkham** [comment]
That's great new, @sodre! Thanks for working on this. 😄

So are you making use of Singularity? If so, you might find [this recent blogpost interesting]( https://www.sylabs.io/2018/11/towards-native-integration-between-singularity-containers-and-kubernetes-announcing-an-open-source-project/ ) (assuming you haven't already read it).

**Comment by sodre** [comment]
I had not seen the post, but it does sound like a good complement to the other packages I have been using.

Do you use it often? Do you use conda within the container as well?

**Comment by sodre** [comment]
Closed by https://github.com/conda-forge/singularity-feedstock/commit/4868babcc88bfd24f0c1c209b56269e1cca55246
