### ISSUE TITLE
`singularity version` from conda reports "47b018f-dirty" instead of "3.6.1"

### ISSUE THREAD

**Issue by mr-c** [conda-forge/singularity-feedstock#22]
See https://github.com/common-workflow-language/cwltool/issues/1332#issuecomment-667143095

To fix this, pull the git tags or set the `VERSION` environment variable before building

**Comment by jakirkham** [comment]
Would you be interested in doing a PR? 😉

**Comment by mr-c** [comment]
Sorry, I don't know anything about conda packaging and I have other
responsibilities at the moment that prevent me from taking the time to
learn.

**Comment by chrisburr** [comment]
Thanks for reporting @mr-c! The fixed build should be deployed within an hour.
