### ISSUE TITLE
Update Singularity version

### ISSUE THREAD

**Issue by rbpatt2019** [conda-forge/singularity-feedstock#36]
Really appreciate the work to make Singularity installable in a Conda environment! I use Singularity/Conda/Snakemake together a fair bit in my work, and would love to take advantage of some of the new versions of Singularity (stable at 3.8.4, though they recently released 3.9.0rc2). Are there any plans to move towards theses versions with the Conda feedstock? If not, I use this enough that I'd be happy to take up some of the maintenance burden, as long as I could get a few pointers on what I need to do!

Thanks for the great work!

**Comment by ngam** [comment]
hi @rbpatt2019, have you tried building it locally? You can fork/clone this repo and then try to `python build-locally.py` and see how it goes. I recommend you start with the working version (3.7.1) and you work upwards. I tried it yesterday after I saw your comment and it didn't work for me... on an ARM64 machine though. Usually you'd want to prepare a `build` conda env with some essential tools to get started. I will try to build it locally on a standard linux machine soon to see if I have any better luck.

I also am interested in helping get this back on track. Not sure if there is a fundamental problem or if the maintainers simply got busy... 

cc @sodre @chrisburr @jakirkham @bgruening

**Comment by ngam** [comment]
@rbpatt2019 also, are there things you badly need in the newer versions or are like radically different/new features? If so, there are some other pretty tortuous ways to get Singularity installed on an HPC without sudo rights... like through linuxbrew or spackio, or even unprivileged builds...

**Comment by bgruening** [comment]
We simply got busy... Any help welcome!

**Comment by chrisburr** [comment]
Yeah the main issue is busyness and the fact the current version is good enough for what I need. I use conda-forge's builds of Singularity extensively at work so help with updating the feedstock would be very appricated! 😄 

Last time I looked at this I ended up needing to add non-trivial patches to get relacatability to work correctly. I made PRs upstream but didn't find the time to finish them: https://github.com/hpcng/singularity/pulls?q=is%3Apr+author%3Achrisburr+is%3Aclosed

Looking now it seems like they've been merged so hoepfully this feedstock can now be updated and have the patches removed 🤞

**Comment by rbpatt2019** [comment]
> @rbpatt2019 also, are there things you badly need in the newer versions or are like radically different/new features? If so, there are some other pretty tortuous ways to get Singularity installed on an HPC without sudo rights... like through linuxbrew or spackio, or even unprivileged builds...

@ngam there aren't any particular features that I'm after, *per se*, I just prefer to always use the most recent software version unless it's incompatible with other software I use.

**Comment by rbpatt2019** [comment]
> Looking now it seems like they've been merged so hoepfully this feedstock can now be updated and have the patches removed 🤞

@chrisburr Good to know! I'm hoping to have some time this afternoon to take a crack at this, and will report back when I can. Apologies in advance for any delays - just adopted a puppy, so life is a little bit hectic!

**Comment by ngam** [comment]
> > @rbpatt2019 also, are there things you badly need in the newer versions or are like radically different/new features? If so, there are some other pretty tortuous ways to get Singularity installed on an HPC without sudo rights... like through linuxbrew or spackio, or even unprivileged builds...
> 
> @ngam there aren't any particular features that I'm after, _per se_, I just prefer to always use the most recent software version unless it's incompatible with other software I use.

Good good!

**Comment by ngam** [comment]
> > Looking now it seems like they've been merged so hoepfully this feedstock can now be updated and have the patches removed 🤞
> 
> @chrisburr Good to know! I'm hoping to have some time this afternoon to take a crack at this, and will report back when I can. Apologies in advance for any delays - just adopted a puppy, so life is a little bit hectic!

No rush! Here's a busy pr https://github.com/conda-forge/singularity-feedstock/pull/38 with a lot going on, basically it all boils down to:
- changing version number and shasum
- rerender 
- fix the patches (deleted two as not needed and slightly edited two more, and left one unchanged)
- @chrisburr fixed an issue with verbosity with travis 
- we currently have two passing builds but the third linux_64 (and maybe most important?) is failing with the unshare library (it's a dep of singularity)

**Comment by ngam** [comment]
Update: I think we have it all figured it out, thanks in large part to @chrisburr --- we just need to clean up the tests now (some issues with mount etc that I think are solvable with --privileged or something like that, i.e.  Idon't think they have anything with the build per se) and this should be all good to go

🥳
