### ISSUE TITLE
MacOS (M1?)

### ISSUE THREAD

**Issue by ngam** [conda-forge/singularity-feedstock#39]
Now that we are up to speed with the latest, how do we feel about trying to add support for MacOS and possibly M1? I haven't had luck even installing Singularity on my M1, so I think this won't actually succeed, but just throwing it out there...

**Comment by chrisburr** [comment]
I'm fairly sure Singularity doesn't support macOS anymore?

If it does, are the necessary parts open sourced? Last time I tried it depended on private forks of open source repos and a big binary blob for the VM image which had a license that didn't allow for redistribution.

**Comment by ngam** [comment]
> I'm fairly sure Singularity doesn't support macOS anymore?
> 
> If it does, are the necessary parts open sourced? Last time I tried it depended on private forks of open source repos and a big binary blob for the VM image which had a license that didn't allow for redistribution.

I think you're right. I couldn't even build it to be honest with a lot of trying and hacking around. So I think this is a dead end for now.
