### ISSUE TITLE
singularity vs singularity-ce

### ISSUE THREAD

**Issue by ngam** [conda-forge/singularity-feedstock#44]
Given these two editions are diverging, and given that HPC admins will likely buy into the commercialized editions (i.e. CE or PRO), I wonder if it makes more sense for us to maintain both Singularity and SingularityCE here. I doubt the differences are going to be big anytime soon, but it is much easier for us to follow their divergence now (see pr #43). 

Three options:
1.  Add new branch with singularity-ce (see https://conda-forge.org/docs/maintainer/updating_pkgs.html#maintaining-several-versions) and starting naming them differently (e.g. we will have singularity 3.9.0 and singularity-ce 3.9.0 out of this feedstock)
2. Do a split recipe here.
3. Start a new standalone feedstock for singularity-ce (see here: https://github.com/conda-forge/staged-recipes/pull/17030)

Either way, we need to clean up our current meta.yaml to correctly reference the upstream repos and docs.

@chrisburr, any thoughts?

**Comment by chrisburr** [comment]
I haven't yet seen any linux distributions shipping `singularity-ce` and the sylabs documentation only talks about installing from source. I also don't think there is much demand at the moment given so similar the projects are so for now I would be inclined to not invest time into `singularity-ce` and see how the situation evolves. All of the HPC use cases I've currently seen ae still committed to the original `hpcng` package. Longer term, I hope either:
* the two forks will be recombined at some point in the future
* one fork will stop being maintained and other Linux distros build their `singularity` package from the other

If you're personally motivated to add `singularity-ce` right now for some reason then it should be in a separate feedstock and marked as conflicting with `singularity` (as I presume it can't be installed alongside?).

**Comment by ngam** [comment]
> given so similar the projects are so for now I would be inclined to not invest time into `singularity-ce` and see how the situation evolves. All of the HPC use cases I've currently seen ae still committed to the original `hpcng` package.

Totally agree on the similarity (they're essentially the same --- basically they copy the features from each right now, it seems). However, I have been seeing more HPC people adopt the sylabs one because of the extra screening and the "security" stuff. I do think your point makes more sense and we shouldn't invest in this anytime soon (I will keep my eye on the divergence to keep us updated). 

Thanks for the speedy response :D
