### ISSUE TITLE
unsquashfs not found (amd64, v3.8.4)

### ISSUE THREAD

**Issue by bcm0** [conda-forge/singularity-feedstock#45]
On amd64 architecture and v3.8.4 (hf1ae047_1) with squashfs-tools v4.4 (h6b73730_2)
this works
```
singularity build --sandbox lolcow docker://godlovedc/lolcow
```
but this fails with **unsquashfs not found**
```
singularity pull docker://godlovedc/lolcow
singularity build --sandbox lolcow lolcow_latest.sif
```

Probably https://github.com/hpcng/singularity/pull/6224 
How can I use this feedstock to build the new upstream version?

**Comment by ngam** [comment]
@adnion I assume we will wait until they have a new release to update. 

In my personal capacity, I can say the following: building locally with Singularity is convoluted without sudo rights, and it is mostly meant to be used by users with the cgroup namespace enabled (i.e. no roots). Two possible workarounds: 
1. use Docker to build locally
2. use the remote builder either completely on the website; or by invoking `singularity build --remote --sandbox`. 

However, if you're not modifying the image like it seems in this case, Singularity will automatically temporarily convert the image to a sandbox, so if you try 

```
singularity pull docker://godlovedc/lolcow
singularity shell lolcow_latest.sif
```

it should work by converting to a temporary sandbox. Could you check either `shell` or `build --remote` and report back?

**Comment by ngam** [comment]
This is an example of what I get (I deleted some info so that the HPC system I am using is not identifiable) 

```bash
~$ singularity pull docker://godlovedc/lolcow
INFO:    Converting OCI blobs to SIF format
WARNING: 'nodev' mount option set on /../.., it could be a source of failure during build process
INFO:    Starting build...
Getting image source signatures
Copying blob 9fb6c798fa41 done  
Copying blob 3b61febd4aef done  
Copying blob 9d99b9777eb0 done  
Copying blob d010c8cf75d7 done  
Copying blob 7fac07fb303e done  
Copying blob 8e860504ff1e done  
Copying config 73d5b1025f done  
Writing manifest to image destination
Storing signatures
2021/11/25 12:14:48  info unpack layer: sha256:9fb6c798fa41e509b58bccc5c29654c3ff4648b608f5daa67c1aab6a7d02c118
2021/11/25 12:14:50  warn rootless{dev/...} creating empty file in place of device 10:175
2021/11/25 12:14:50  warn xattr{dev/...} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
...
INFO:    Creating SIF file...
~$
```

```bash
~$ singularity shell lolcow_latest.sif 
INFO:    Converting SIF file to temporary sandbox...
Singularity> 
```

```bash
Singularity> exit
exit
INFO:    Cleaning up image...
~$
```

Let us know if this doesn't cover your use cases and we can probe this further.

**Comment by bcm0** [comment]
I need ibm power cpu architecture and a sandbox directory for development.
How can I use this feedstock to build my own version?

**Comment by ngam** [comment]
> I need ibm power cpu architecture and a sandbox directory for development.

Can you say more explicitly what you would like to do? Are you looking to edit the contents of the image directly? This will likely not work unless the admins have set up everything correctly for mounting, etc. --- generally, imo, it is better to never really edit the content of the image and just use it as a module to run and modify other files outside of it. You can always build (e.g. using the sylabs remote builder) with the edits you'd like. We do have the package for ppc, but when it comes to images, I have little experience in converting images from amd64 to ppc (if that's what you're trying to do).

> How can I use this feedstock to build my own version?

This is relatively easy. Fork this repo (singularity-feedstock) and then clone it on your machine. You have two options from there: When you're in the root directory of this repo, (1) you can build it via `python build-locally.py` (you need Docker for this to work) or (2) you can do `conda build .` (after installing conda-build) or `conda mambabuild .` (after installing mamba and boa). If you're just updating to the upstream version, you can edit the url in recipe/meta.yaml and that should do it.

**Comment by ngam** [comment]
(I can also help you build the upstream version natively, depending if you're a user or admin on the machine --- can you try `lsns` on the machines of interst and see if `cgroup` is one of the listed namespaces?)

**Comment by bcm0** [comment]
WOW your help and instructions are superb. I commented out the patches in meta.yml and built both upstream and 3.8.4 with (1) and it works. (2) complained about go-deps missing.
I guess one of the patches breaks unsquashfs.

**Comment by ngam** [comment]
> I guess one of the patches breaks unsquashfs

Interesting. I will initiate a new build without the patches to see how it goes.

**Comment by ngam** [comment]
pr #46

**Comment by ngam** [comment]
@adnion I tried building without the patches and the tests failed, actually with the error you reported (unsquashfs not found). Could you confirm that you actually removed the patches? Also, which one did you build for? ppc? For ppc, we skip some tests because we've been having issues with running docker with `--privileged` flag...

**Comment by bcm0** [comment]
@ngam i confirm that the only change i did was commenting out the whole patches block in meta.yml. I built for linux-64 and the tests failed after the singularity --version grep test.
I installed the broken package in a new conda environment and tried the remaining test cases manually and the one in my first post of course and all work. I skipped the 4 tests below # Ensure we are using conda's CNI

**Comment by ngam** [comment]
Okay, thanks. While this may work for you, it is hard to know if it will work for everyone. And yes, the tests passed for that portion in my runs as well. Fwiw, we will likely need to eliminate more the patches in the next few versions (they are changing the code and thus are unneeded).

I am also trying to have SingularityCE up on conda-forge as well; there seems to be a bit of divergence beginning between the HPCng and Sylabs (e.g. currently SingularityCE is at 3.9.1 while Singularity is at 3.8.4 --- while they do still copy each other, they are quite independent and they do their own thing; because Sylabs' SingularityCE is backed by a commercial entity, their development seems faster and more focused...)

If you are interested: https://github.com/conda-forge/staged-recipes/pull/17084
